spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: gitpod
        password: postgres
        driverClassName: org.postgresql.Driver
springdoc:
    api-docs:
        path: /api-docs
